version: '3.9'
services:
  blockchain-iot:
    build: 
      context: .
      # Choose 'development' for build with dev and test dependencies
      # Choose 'test' for build that runs unit and coverage tests automatically
      # Remove this target or set to 'production' for build with production dependencies
      target: development
    env_file:
      - .env
    image: blockchain-iot:latest
    environment:
      - TZ=America/Sao_Paulo
      - ENVIRONMENT=dev
    # networks:
    #   - blockchain-iot
    volumes:
      - ${PWD}:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: blockchain-iot
    networks:
       - mqtt-docker_net
        

networks:
  mqtt-docker_net:
    external: true